# Generated by Django 2.1.12 on 2020-02-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afordeal88scrumy', '0002_auto_20200115_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrumygoals',
            name='goal_name',
            field=models.CharField(max_length=255),
        ),
    ]
